version: "3.8"
services:
  backend:
    build: ./backend # Path to your Node.js application
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend # Path to your React application
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
